#!/usr/env/bin bash
# Sets environment variables for this project

export QM_MYSQL_USER='qm_dev'
export QM_MYSQL_PWD='qm_dev_pwd'
export QM_MYSQL_HOST='localhost'
export QM_MYSQL_DB='qm_dev_db'
export QM_ENV='dev'
